import pandas as pd
import json
import os

# -*- coding: utf-8 -*-
"""convert_json_lane.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ud1YarMWW_m8bIkldPKg6QNl-GJuUwqR
"""

def lane_convert_via(label_path):
  '''라벨 json 폴더명을 문자열로'''
  cnt = 0
  all_dic = {}
  labels_json = os.listdir(label_path)
  for label_json in labels_json:
    with open(f'{label_path}/{label_json}') as file:
      js = json.load(file)
      dic = {}
      dic['fileref'] = ""
      dic['size'] = js['image']['image_size'][0]*js['image']['image_size'][1]
      dic['filename'] = js['image']['file_name']
      dic['base64_img_data']= ""
      dic['file_attributes']= { }
      dic['regions'] = {} # 한 이미지에서 탐지되는 클래스 수


      for i in range(len(js['annotations'])):
        class_label = js['annotations'][i]['class']
        attr_labels = js['annotations'][i]['attributes']
        st = str(class_label)+'_'

        for al in attr_labels:
          if len(al)!=0:
            st += al['value']+'_'
        st = st[:-1]
        if st == 'traffic_lane_yellow_solid':
            pass
        else:
            continue
        df = pd.DataFrame(js['annotations'][i]['data'])
        dic['regions'][i] = {
            'region_attributes':{
                'label': st,
            },
            'shape_attributes': {
                "name": js['annotations'][i]['category'],
                "all_points_x":list(df['x']),
                "all_points_y":list(df['y'])
            }
        }
      if len(dic['regions']) != 0:
        all_dic['lane_'+js['image']['file_name']] = dic
        cnt += 1
    # if cnt == 300:
    #   break
  print(f'{len(all_dic)}개의 라벨 데이터') # 개수를 알기 위한
  with open('E:/차선-횡단보도 인지 영상(수도권)/Validation/input.json', 'w') as file:
    json.dump(all_dic, file)
    print("input.json 파일로 저장 완료")
  return all_dic

lane_convert_via("E:/차선-횡단보도 인지 영상(수도권)/Validation/json_path")